name: Mesen-X-libretro Linux x86_64

on:
  #push:
  workflow_dispatch:
  watch: # this is a hack that lets repo owners trigger a build by starring
    types: [started]
    if: github.actor == github.event.repository.owner.login

jobs:
  Linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
    - name: Install needed packages
      run: sudo apt install wget git build-essential
    - name: Checkout source
      run: git clone https://github.com/NovaSquirrel/Mesen-X.git && cd Mesen-X && git submodule update --init
    - name: Build libretro core
      working-directory: Mesen-X
      run: |
        cd Libretro
        make -j8
        wget https://raw.githubusercontent.com/libretro/libretro-super/master/retrolink.sh && chmod +x retrolink.sh && ./retrolink.sh mesen_libretro.so
        zip -9 ../../mesen_libretro.so.zip mesen_libretro.so
    - name: Create new release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: Linux_64-bit
        file: mesen_libretro.so.zip
        overwrite: true
