name: px68k-libretro Linux x86_64

on:
  #push:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
  watch: # this is a hack that lets repo owners trigger a build by starring
    types: [started]
    if: github.actor == github.event.repository.owner.login

jobs:
  Linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
    - name: Install needed packages
      run: sudo apt install wget git build-essential
    - name: Checkout source
      run: git clone https://github.com/negativeExponent/px68k-libretro.git && cd px68k-libretro && git submodule update --init
    - name: Check gcc version
      run: |
        gcc --version
        g++ --version
    - name: Build libretro core
      working-directory: px68k-libretro
      run: |
        make -j8
        wget https://raw.githubusercontent.com/libretro/libretro-super/master/retrolink.sh && chmod +x retrolink.sh && ./retrolink.sh px68k_libretro.so
        zip -9 ../px68k_libretro.so.zip px68k_libretro.so
    - name: Create new release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: Linux_64-bit
        file: px68k_libretro.so.zip
        overwrite: true
