name: Mesen-X-libretro Windows x86_64

on:
  #push:
  workflow_dispatch:
  #schedule:
    #- cron: '0 2 * * *' # run at 2 AM UTC
  #watch: # this is a hack that lets repo owners trigger a build by starring
    #types: [started]
    #if: github.actor == github.event.repository.owner.login

jobs:
  Windows:
    name: Build for Windows via cross-compile
    runs-on: ubuntu-latest
    container: ubuntu:kinetic
    steps:
    - name: Install needed packages
      run: |
        apt-get update
        apt-get install -yq wget git build-essential mingw-w64 mingw-w64-x86-64-dev mingw-w64-tools
    - name: Checkout source
      run: git clone https://github.com/NovaSquirrel/Mesen-X.git && cd Mesen-X && git submodule update --init
    - name: Build libretro core
      working-directory: Mesen-X
      run: |
        /usr/bin/x86_64-w64-mingw32-gcc --version
        /usr/bin/x86_64-w64-mingw32-g++ --version
        gcc --version
        cd Libretro
        make CC=/usr/bin/x86_64-w64-mingw32-gcc CXX=/usr/bin/x86_64-w64-mingw32-g++ platform=win -j8
        strip -s mesen_libretro.dll
        zip -9 ../../mesen_libretro.dll.zip mesen_libretro.dll
    - name: Create new release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: Windows_64-bit
        file: mesen_libretro.dll.zip
        overwrite: true
