# This is a basic workflow to help you get started with Actions

name: Mesen-X-libretro Win x86_64 (Msys2)

# Controls when the workflow will run
on:
  push:
  #schedule:
    #- cron: '0 2 * * *' # run at 2 AM UTC
  workflow_dispatch:
  watch: # this is a hack that lets repo owners trigger a build by starring
    types: [started]
    if: github.actor == github.event.repository.owner.login

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Windows:
    name: Build for Windows using msys2
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: msys2/setup-msys2@v2
        with:
          release: false
          update: false
          install: >-
            base-devel
            git
            wget
            zip
            ccache
      - shell: msys2 {0}
        run: |
          whereis ccache
          uname -a
          gcc --version
          export PATH=/usr/lib/ccache/bin:$PATH
          git clone https://github.com/NovaSquirrel/Mesen-X.git && cd Mesen-X && git submodule update --init
          cd Libretro
          make -j8
          strip -s mesen_libretro.dll
          zip -9 ../../mesen_libretro.dll.zip mesen_libretro.dll
      - name: Create new release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: Windows_64-bit
          file: mesen_libretro.dll.zip
          overwrite: true
