name: Mesen-X-libretro Windows x86_64 (Msys2)

on:
  push:
  #schedule:
    #- cron: '0 2 * * *' # run at 2 AM UTC
  workflow_dispatch:
  watch: # this is a hack that lets repo owners trigger a build by starring
    types: [started]
    if: github.actor == github.event.repository.owner.login

jobs:
  Windows:
    name: Build for Windows via Msys2 cross-platform
    runs-on: windows-latest
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: update
          install: >-
            base-devel
            gcc
            git
            make
            zip
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-ntldd
            mingw-w64-x86_64-zlib
            mingw-w64-x86_64-pkg-config
      - name: Checkout source
        run: git clone https://github.com/NovaSquirrel/Mesen-X.git && cd Mesen-X && git submodule update --init
      - name: Build libretro core
        shell: msys2 {0}
        working-directory: Mesen-X
        run: |
          cd Libretro
          make -j8
          strip -s mesen_libretro.dll
          zip -9 ../../mesen_libretro.dll.zip mesen_libretro.dll
      - name: Create new release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: Windows_64-bit
          file: mesen_libretro.dll.zip
          overwrite: true
